spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rajkiran047@gmail.com
    password: tiqb ntux qncu ugzt
    display: Raj Kiran
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.ssl.protocols: TLSv1.2