spring:
  mail:
    host: smtp.hostinger.com
    port: 465
    username: info@marketdeed.com
    password: Marketdeed123@123!
    display: marketdeed
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false   # disable STARTTLS when using SSL port 465
      mail.smtp.ssl.enable: true         # enable SSL for port 465
      mail.smtp.ssl.trust: smtp.hostinger.com
      mail.smtp.ssl.protocols: TLSv1.2